version: "3.9"

services:
  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Sync local project with /app inside container
    command: uvicorn mcp_server:app --host 0.0.0.0 --port 8000 --reload