version: "3.9"

services:
  mcp_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Sync local project with /app inside container
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://mcpsuper:mysecurepass@db:5432/mcpdb
    command: uvicorn mcp_server:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    restart: always
    container_name: mcp_postgres
    environment:
      POSTGRES_USER: mcpsuper
      POSTGRES_PASSWORD: mysecurepass
      POSTGRES_DB: mcpdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: